"""Add index to user_id

Revision ID: e16a0b65e595
Revises: b5916ba7417b
Create Date: 2025-04-22 20:13:16.067634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16a0b65e595'
down_revision: Union[str, None] = 'b5916ba7417b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_todos_user_id'), 'todos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_user_id'), table_name='todos')
    # ### end Alembic commands ###
